# File: backend/backend_app.py

from flask import Flask, request, jsonify
from flask_cors import CORS
import google.generativeai as genai
import os
import subprocess
import tempfile
import time
import serial
import threading

# Import API key from local config
try:
    from config import GEMINI_API_KEY
except ImportError:
    GEMINI_API_KEY = None

app = Flask(__name__)
CORS(app)

if GEMINI_API_KEY is None:
    print("❌ GEMINI_API_KEY not found. Please create config.py based on config_template.py")
    exit(1)

# Configure Gemini API key
genai.configure(api_key=GEMINI_API_KEY)

# Initialize generative models
prompt_refiner_model = genai.GenerativeModel('gemini-2.5-flash-preview-05-20')
coder_model = genai.GenerativeModel('gemini-2.5-flash-preview-05-20')

# Global variables for serial communication
serial_monitor_output = []
serial_read_thread = None
serial_port_object = None
stop_serial_read_event = threading.Event()

def read_serial_port(port, baud_rate):
    global serial_port_object, serial_monitor_output
    serial_monitor_output = []
    try:
        if serial_port_object and serial_port_object.is_open:
            serial_port_object.close()
        serial_port_object = serial.Serial(port, baud_rate, timeout=1)
        print(f"Opened serial port {port} at {baud_rate} baud.")
        time.sleep(2)
        while not stop_serial_read_event.is_set():
            if serial_port_object.in_waiting > 0:
                line = serial_port_object.readline().decode('utf-8', errors='ignore').strip()
                if line:
                    serial_monitor_output.append(line)
                    print(f"Serial: {line}")
            time.sleep(0.01)
    except serial.SerialException as e:
        print(f"Error opening serial port {port}: {e}")
        serial_monitor_output.append(f"ERROR: Could not open serial port: {e}")
    finally:
        if serial_port_object and serial_port_object.is_open:
            serial_port_object.close()

@app.route('/generate_code_and_upload', methods=['POST'])
def generate_code_and_upload_route():
    global serial_read_thread, serial_port_object, stop_serial_read_event
    data = request.json
    user_prompt = data.get('prompt')
    esp32_port = data.get('esp32_port', '/dev/ttyUSB0')

    board_fqbn = "esp32:esp32:esp32"
    baud_rate = 115200

    if not user_prompt:
        return jsonify({"error": "Prompt is required"}), 400

    current_code = ""
    full_output_log = []
    max_retries = 3

    for retry_count in range(max_retries):
        try:
            full_output_log.append(f"\n--- Attempt {retry_count + 1}/{max_retries} ---")

            if retry_count == 0:
                code_instruction = f"Generate a complete Arduino ESP32 sketch based on the prompt: '{user_prompt}'"
                code_response = coder_model.generate_content(code_instruction)
                current_code = code_response.text.strip("```cpp").strip("```").strip()
                full_output_log.append("Initial code generated by AI.")
            else:
                rectification_prompt = f"""
                The previous Arduino ESP32 code failed. Correct it.

                Original Code:
                ```cpp
                {current_code}
                ```

                Errors:
                ```
                {os.linesep.join(full_output_log[-10:])}
                ```
                """
                rectification_response = prompt_refiner_model.generate_content(rectification_prompt)
                current_code = rectification_response.text.strip("```cpp").strip("```").strip()
                full_output_log.append("AI provided rectified code.")

            with tempfile.TemporaryDirectory() as tmpdir:
                sketch_path = os.path.join(tmpdir, "auto_generated_sketch")
                os.makedirs(sketch_path)
                ino_file_path = os.path.join(sketch_path, "auto_generated_sketch.ino")
                with open(ino_file_path, "w") as f:
                    f.write(current_code)
                full_output_log.append(f"Code saved: {ino_file_path}")

                compile_command = ["arduino-cli", "compile", "--fqbn", board_fqbn, sketch_path]
                full_output_log.append(f"Compile: {' '.join(compile_command)}")
                compile_result = subprocess.run(compile_command, capture_output=True, text=True, check=True)
                full_output_log.append("Compilation successful.")
                full_output_log.append(compile_result.stdout)

                upload_command = ["arduino-cli", "upload", "--fqbn", board_fqbn, "--port", esp32_port, sketch_path]
                full_output_log.append(f"Upload: {' '.join(upload_command)}")
                upload_result = subprocess.run(upload_command, capture_output=True, text=True, check=True)
                full_output_log.append("Upload successful.")
                full_output_log.append(upload_result.stdout)

                # Serial check
                if serial_read_thread and serial_read_thread.is_alive():
                    stop_serial_read_event.set()
                    serial_read_thread.join(timeout=2)
                    stop_serial_read_event.clear()
                serial_monitor_output.clear()
                stop_serial_read_event.clear()
                serial_read_thread = threading.Thread(target=read_serial_port, args=(esp32_port, baud_rate))
                serial_read_thread.daemon = True
                serial_read_thread.start()

                start_time = time.time()
                esp32_ready = False
                while time.time() - start_time < 30:
                    if "ESP32 Ready!" in serial_monitor_output:
                        esp32_ready = True
                        break
                    time.sleep(1)
                if serial_read_thread and serial_read_thread.is_alive():
                    stop_serial_read_event.set()
                    serial_read_thread.join(timeout=2)
                    stop_serial_read_event.clear()

                if esp32_ready:
                    full_output_log.append("ESP32 Ready confirmed ✅")
                    return jsonify({"success": True, "generated_code": current_code, "output_log": "\n".join(full_output_log)})
                else:
                    full_output_log.append("ESP32 did not confirm readiness. Retrying...")
                    continue

        except subprocess.CalledProcessError as e:
            full_output_log.append(f"Compilation/Upload failed:\n{e.stdout}\n{e.stderr}")
            continue
        except Exception as e:
            full_output_log.append(f"Unexpected error: {e}")
            return jsonify({"success": False, "generated_code": current_code, "output_log": "\n".join(full_output_log)})

    full_output_log.append(f"Failed after {max_retries} attempts.")
    return jsonify({"success": False, "generated_code": current_code, "output_log": "\n".join(full_output_log)})

if __name__ == '__main__':
    app.run(debug=True, port=5000)
